# -*- coding: utf-8 -*-
"""weather_tool.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m2Yn3tBNLNHqRakowrJ_qxRYU_eBO0X7
"""

import requests

def get_current_weather(city_name="Hyderabad"):
    try:
        # 1. GEOCODING (Find Lat/Lon)
        # Timeout set to 3 seconds to prevent freezing if internet is bad
        geo_url = f"https://geocoding-api.open-meteo.com/v1/search?name={city_name}&count=1&language=en&format=json"
        geo_res = requests.get(geo_url, timeout=3).json()

        if "results" not in geo_res:
            return "Weather unavailable (City not found)."

        location = geo_res["results"][0]
        lat = location["latitude"]
        lon = location["longitude"]

        # 2. GET WEATHER (With Rain Codes)
        # We request temperature, wind, and the 'weathercode'
        weather_url = f"https://api.open-meteo.com/v1/forecast?latitude={lat}&longitude={lon}&current_weather=true"
        w_res = requests.get(weather_url, timeout=3).json()

        current = w_res["current_weather"]
        temp = current["temperature"]
        wind = current["windspeed"]
        code = current["weathercode"]

        # 3. DECODE THE RAIN (Convert number to text)
        condition = "Unknown"
        rain_warning = "" # Empty unless it's actually raining

        if code == 0:
            condition = "Clear Sky ☀️"
        elif code in [1, 2, 3]:
            condition = "Cloudy ☁️"
        elif code in [45, 48]:
            condition = "Foggy 🌫️"
        elif code in [51, 53, 55, 61, 63, 65, 80, 81, 82]:
            condition = "Rainy 🌧️"
            rain_warning = " (WARNING: It is raining. Do not spray pesticides!)"
        elif code >= 95:
            condition = "Thunderstorm ⛈️"
            rain_warning = " (WARNING: Storm detected.)"

        # 4. FINAL OUTPUT
        return f"Weather in {city_name}: {temp}°C, Condition: {condition}, Wind: {wind} km/h.{rain_warning}"

    except requests.exceptions.ConnectionError:
        return "Weather unavailable (No Internet)."
    except Exception as e:
        return f"Weather Error: {e}"

# Test it
if __name__ == "__main__":
    # You can change this to "London" (usually rainy) to test the rain warning
    print(get_current_weather("Hyderabad"))